// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using StudentProject.Models;

#nullable disable

namespace StudentProject.Migrations
{
    [DbContext(typeof(StudentContext))]
    partial class StudentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("StudentProject.Models.Student", b =>
                {
                    b.Property<string>("Rollno")
                        .HasColumnType("text");

                    b.Property<string>("Class")
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .HasColumnType("text");

                    b.Property<string>("StudentFirstName")
                        .HasColumnType("text");

                    b.Property<string>("StudentLastName")
                        .HasColumnType("text");

                    b.Property<int>("YearofEnrollment")
                        .HasColumnType("integer");

                    b.HasKey("Rollno");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
